







	



.build/alamode/EEPROM/EEPROM.d : /usr/share/arduino/libraries/EEPROM/EEPROM.cpp
	@mkdir -p .build/alamode/EEPROM
	@/usr/bin/avr-gcc -mmcu=atmega328p -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SoftwareSerial  -MM $^ > $@
	
	@printf ".build/alamode/EEPROM/EEPROM.d .build/alamode/EEPROM/" | cat - $@ > $@~ && mv $@~ $@



.build/alamode/EEPROM/dependencies.d : .build/alamode/EEPROM/EEPROM.d
	@echo [96mScanning dependencies of EEPROM[0m
	@mkdir -p .build/alamode/EEPROM
	@cat $^ > $@;

all : .build/alamode/EEPROM/dependencies.d
	@true

